### ISSUE TITLE
Создать примерную начальную базу данных

### ISSUE THREAD

**Issue by Safi51** [AttractorSchool/ESPD-APHP1#1]
### Конченый результат:

- Создать начальную базу данных который можно работать

### План решения:
- Создание table для разных сущностей 
- Сделать миграции 
- Добавление Фабрик и сидов
- Создание моделей

### Критерий приемки:

- При обращение к подпискам по имение выходять все имена подписчиков(резидентов)

**Comment by khalfin1994** [comment]
Закончил без привязанных к таску коммитов и пуша, т.к. запушил до создания тикета.
