### ISSUE TITLE
Начальная верстка уведомлении

### ISSUE THREAD

**Issue by Arystanbek360** [AttractorSchool/ESPD-APHP1#15]
### Конечный результат:
Создать вторую страницу networking в контроллере PageController с методом notifications который возвращает view, blade должен быть расположен в папке ../front/notifications.blade.php

### План решения:
в блейд выводить всех рузидентов авторизованного пользователя(где хотят с вами пообщаться но вам нужно дать approve для дальнейшего общения)
во время назначения роута ссылка должна вести на страницу '../notifications' сам роут назвать как 'notifications'
По поводу верстки сверстать как указано на макете (допустимы мелкие не соответствия) 
<img width="302" alt="notificate" src="https://github.com/AttractorSchool/ESPD-APHP1/assets/125344466/ea2ccb35-5454-4a80-8d41-8967d4369457">

### Критерии приёмки:
карточки должны быть выведены с помощью foreach.
карточка должна быть расположена по горизонтали как на макете(на нем должно быть размешено фото(заглушка),ФИО пользователя который хочет с вами с конектиться,и количество конектов у данного пользователя и в конце карточки должна быть ссылка в виде кнопки(btn btn-primary)) текст на странице расположить прижатым к левому краю,текст на кнопке должен быть центрирован

### Реальное время работы

**Comment by Safi51** [comment]
### Планируемое время: 3ч
### Реальное время работы 4ч
