### ISSUE TITLE
Реализовать страницу с чатом

### ISSUE THREAD

**Issue by Arystanbek360** [AttractorSchool/ESPD-APHP1#16]
### Конечный результат:
Создать контроллере ChatController с методом send который возвращает json,c методом show который тоже возвращает json обект и методом chat chat который возвращает view, blade должен быть расположен в папке ../front/chat.blade.php
### План решения:
blade должен выглядеть максимально просто.
Примерно таким образом:
<img width="500" alt="massage" src="https://github.com/AttractorSchool/ESPD-APHP1/assets/125344466/4f5197a7-e0dd-405b-ae0c-573aa931f7aa">
Есть один общий див в котором есть 3 внутрених дива:
в 1 диве верхнем должна быть информация о пользователе с кем ведется переписка
во 2 диве должна быть id="messages"
в 3 диве должна находиться форма:
с такими полями: 'response_id'=>hidden,'body'=>text
Для упрощения как выглядит база данных и что нужно будет примерно проделать(тут не верно указано названия роута) :
<img width="1388" alt="chat" src="https://github.com/AttractorSchool/ESPD-APHP1/assets/125344466/84090340-a643-4cfd-b33a-07917fe218f1">

### Критерии приёмки:
Реализовать ajax запрос на сервер:
1)при переходе на старницу "../chat/{response_id}" открывается страница с формой при нажатии на кнопочку отправить выполняется ajax запрос на Route::post('/message', [ChatController::class, 'send'])->name('chat.send'); где происходить запись в базу данных и валидация всех доступных полей и возвращается json
2)возвращенный json формат должен распарситься и отобразиться в div где id="messages"
пока все сообщения выводить по правую сторону без всяких проверок и так далее

### Реальное время работы

**Comment by Amalbek00** [comment]
Done

**Comment by Amalbek00** [comment]
**Планируемое время: 4ч
Реальное время работы - 8ч**
