### ISSUE TITLE
Реализация 'connect'-'Дружба' в проекте

### ISSUE THREAD

**Issue by Arystanbek360** [AttractorSchool/ESPD-APHP1#17]
### Конечный результат:
Создать контроллере ActionController с методом connect который возвращает back()->with(['status' => ....]);

### План решения:
В методе connect авторизованный пользователь принимает приглашения для перехода в чат. 
Реализация должна быть примерно такого образа:
$response = Response::where -> где авторизванный пользователь равен first_id или second_id и так же id_пользователь_номер_2  который прихоидт с помощью request или по ссылке-аргумент(на ваше усмотрение) 

### Критерии приёмки:
1)если пустой респонс ->тогда создаем новый респонс new Response и передаем id первого и второго пользователя и ставим true отправителю. 
2)если есть респонс то делаем проверку:
2.1)Авторизованный Пользователь отправитель и ждет подтверждения тогда отправляем 'status'=>"В обработке"
2.2)Авторизованный Пользователь получатель и должен подтвердить, тогда в поле confirm_second меняем на true и отправляем 'status'=>"В обработке"

Метод можете выбрать сами реализовывать через post запрос или get:
Route::post('/confirm', [ActionController::class, 'connect'])->name('connect');
Route::get('/confirm/{user_id}', [ActionController::class, 'connect'])->name('connect');
Примечание:если 'connect' будет реализован с помощью post запроса то обязательно сделать валидацию!
### Реальное время работы

**Comment by Timur211** [comment]
Планируемое время работы: с 19:00 - 00:00 [09.07.2023 - 10.07.2023]

**Comment by Timur211** [comment]
Фактическое время работы: c 19:30 - 22:30 [09.07.2023]

**Comment by Timur211** [comment]
**Планируемое время: 2ч
Реальное время работы 1.5ч**
