### ISSUE TITLE
Верстка хэдера и футера в начальныой странице

### ISSUE THREAD

**Issue by Safi51** [AttractorSchool/ESPD-APHP1#2]
### Конечный результат:

- Реализовать верстку хэдера и футера для последущих страниц на Ларавел

### Мотивация

- Для легкового перехода между страницами сайта для юзеров

### План решения

- Реализовать навбар с кнопками Войти и Членство
- Реализовать кнопку футер
- Для мобильного разрешения
- Примерный вид
![image](https://github.com/AttractorSchool/ESPD-APHP1/assets/108079889/8c4911f2-fdbf-4ec3-90b9-82099ca765b5)
![image](https://github.com/AttractorSchool/ESPD-APHP1/assets/108079889/24e4701f-c34a-47aa-816b-db55c1385084)

### Критерий приемки:

- При загрузке главной страницы на экране пользователь должен видеть навбар с кнопками Women create club, События, Нетворкинг, Менторство, Академия,  Войти, Членство
- При нажатие на кнопки Менторство и Академии и Войти, если пользователь не зарегистрирован  должно кидать на страницу войти с возможностью регистрации
- Футер с соц-сетями
- Адаптированная верстка для мобильного разрегения

### Реальное время работы

**Comment by khalfin1994** [comment]
Completed
