### ISSUE TITLE
Стилизация текста сообщении и добавление css свойств

### ISSUE THREAD

**Issue by Arystanbek360** [AttractorSchool/ESPD-APHP1#20]
### Конечный результат:
откоректировать верстку чата для отображения текста слева и справа как в других социальных сетях
### План решения:
Реализовано должно быть с помощью JS
тот текст (сообщении) который вы оборачиваете в див нужно добавлять к нему класс (me,other) для работы с ними добавить css файл
### Критерии приёмки:
Верстка должна быть выглядеть примерно таким образом
<img width="491" alt="massage" src="https://github.com/AttractorSchool/ESPD-APHP1/assets/125344466/3725fc9d-c398-4e3e-a534-23036ad30b7d">
### Реальное время работы

**Comment by Amalbek00** [comment]
Вщту

**Comment by Amalbek00** [comment]
Done

**Comment by Amalbek00** [comment]
Планируемое время: 6ч
Реальное время работы - 10ч
