### ISSUE TITLE
Реализация чата

### ISSUE THREAD

**Issue by Timur211** [AttractorSchool/ESPD-APHP1#30]
### **Конечный результат:**
Реализовать вёрстку чата (mobile first)

### **План решения:**
Вёрстка должна быть таким образом:
![image](https://github.com/AttractorSchool/ESPD-APHP1/assets/56838167/72b26812-bb6c-44c3-8b52-b889776709d3)

### **Критерии приёмки:**
- Вёрстка должна быть в первую очередь под мобильные устройства
- Новые сообщения желательно отображаться желательно без перезагрузки страницы
- При поступления новых сообщений показывать их в самом вверху списка

### **Планируемое время работы:**
Если просто верстка тогда часа 2
Если создания контроллера и вывод доступных чатов где есть авторизованный пользователь с выводом последних сообщении тогда 7-9ч

### **Реальное время работы**
10 ч

**Comment by Arystanbek360** [comment]
В процессе

**Comment by Arystanbek360** [comment]
Выполнял 1ч: за это время успел реализовать метод в моделе Респонс которая вытаскивает только последнее сообщение по нужным параметрам,а именно по id авторизованного пользователя и достает последнее сообщение

**Comment by Arystanbek360** [comment]
Выполнял 4.5ч : за это время успел реализовать метод в моделе Респонс который возвращает готовую верстку верстку для чата и подставляет ссылку на переход на нужную страницу,  реализовал query запрос для получения нужной информации $responses = Response::where(function ($query) use ($user) {
            $query->where('first_id', $user->id)
                ->orWhere('second_id', $user->id);
        })
            ->where('confirm_first', true)
            ->where('confirm_second', true)
            ->get();. 
Еще реализовал корректную верстку вместе с сылками и информацией когда была начата переписка и с последним текстом который не ломает верстку большим сообщением
Осталось еще реализовать: Вывод нужного Имя с кем ведется переписка и узнать можно ли принтить верстку из модели в html.

**Comment by Arystanbek360** [comment]
Выполнил в общем за 10 часов. Вывод пройсходит полностью через блейд в моделе была убрана метод print так как сказали не желательно реализовывать с помощью принта. и пробемы были во время пуша. Закинул вначале не на ту ветку потом откатился и пришлось перелапатить свой код чтобы востановить все. Как востановил свой код вручную пришлось снова вазиться из-за конфликта и устранять конфликт
