### ISSUE TITLE
Исправление вёрстки Чата

### ISSUE THREAD

**Issue by Timur211** [AttractorSchool/ESPD-APHP1#31]
### **Конечный результат:**
Исправление вёрстки чата (mobile first)

### **План решения:**
Тикет https://github.com/AttractorSchool/ESPD-APHP1/issues/20 ранее имплементированный, решить проблему с вёрсткой на мобильной адаптации, примерный макет:
![image](https://github.com/AttractorSchool/ESPD-APHP1/assets/56838167/61cedc70-74e3-4939-a08a-51ea97203fdb)

### **Критерии приёмки:**
- Страница чата корректно отображаются на мобильных устройствах
- Оформление страницы соответствует заданному макету
- Функциональность страниц также корректно работают, элементы не съезжают 
- При объёмных сообщениях вёрстка чата не должна ломаться
- Отображать информацию и картинку пользователя в чате
### **Планируемое время работы:**
5 ч
### **Реальное время работы**
4.5 ч

**Comment by Arystanbek360** [comment]
done

**Comment by Arystanbek360** [comment]
Никаких проблем не было. Для красоты было бы еще лучше если выводилось время отправки сообщения
