### ISSUE TITLE
Исправление вёрстки Футера и Главной страницы

### ISSUE THREAD

**Issue by Timur211** [AttractorSchool/ESPD-APHP1#32]
### **Конечный результат:**
Исправление вёрстки главной страница и футера (mobile first)

### **План решения:**
Тикет https://github.com/AttractorSchool/ESPD-APHP1/issues/21 ранее уже реализованный, подкорректировать футер, чтобы не слетала вёрстка
Тикет https://github.com/AttractorSchool/ESPD-APHP1/issues/3 с реализованной главной страницой, подкорректировать вёрстку, исправить проблемы с адаптивностью, расположением элементов
![image](https://github.com/AttractorSchool/ESPD-APHP1/assets/56838167/7bfa8eaa-4483-457a-998b-00bf6634030c)

На главной странице подправить элементы: картинки и карусели, иконки (arrow-right, arrow-left) отцентровать относительно картинок
https://prnt.sc/Im9SRpsopD9v
### **Критерии приёмки:**
- Оформление футера и главной страницы соответствует заданному макету
- Функциональность также корректно работают, элементы не съезжают 
### **Планируемое время работы:**
2 ч
### **Реальное время работы**
2 ч

**Comment by Arystanbek360** [comment]
done

**Comment by Arystanbek360** [comment]
Никаких проблем не было
