### ISSUE TITLE
Исправление NETWORK

### ISSUE THREAD

**Issue by Timur211** [AttractorSchool/ESPD-APHP1#33]
### **Конечный результат:**
Исправление вёрстки NETWORK (mobile first)

### **План решения:**
Тикет https://github.com/AttractorSchool/ESPD-APHP1/issues/14  реализованный, внести коррективы в вёрстку на мобильной адаптации, стилизовать под данный макет:
![image](https://github.com/AttractorSchool/ESPD-APHP1/assets/56838167/ab89e809-467b-4336-ac5d-413ce03d4fdc)
Сделать проверку, чтобы в нетворкинге не видеть себя в списке. Циклом пройтись и отобразить имена резидентов.
После того как нажать, сделать кнопку неактивной и поменять текст на ЗАПРОШЕНО, пример кнопки:
![image](https://github.com/AttractorSchool/ESPD-APHP1/assets/56838167/16fd949f-2df3-44c3-9240-9b2f726f4c34)

### **Критерии приёмки:**
- Страница network корректно отображаются на мобильных устройствах
- Оформление страницы соответствует заданному макету
- Функциональность страниц также корректно работают, элементы не съезжают 
- Убедиться, что функциональность страницы работает корректно. Проверить, что список резидентов отображается правильно и не включает текущего пользователя. После отправки запроса на соединение с резидентом, убедиться, что кнопка становится неактивной и текст на ней изменяется на "ЗАПРОШЕНО".
-Проверить взаимодействие элементов страницы между собой. Проверить, что все кнопки и ссылки реагируют на нажатия и выполняют соответствующие действия без ошибок.
### **Реальное время работы**

**Comment by Amalbek00** [comment]
In process

**Comment by Amalbek00** [comment]
Done
