### ISSUE TITLE
Создать таблицы (Роли, интересы, тестирование, подписки)

### ISSUE THREAD

**Issue by Timur211** [AttractorSchool/ESPD-APHP1#36]
### **Конечный результат:**
Создать модели Роль, Интерес, Тестирование, Подписка, также если требуется фабрики и сиды
### **План решения:**
- Разработать модель "Роль", есть 3 роли (Пользователь, Ментор, Админ).
- Создать модель "Интерес" для представления интересов пользователей
- Реализовать модель "Тестирование" для хранения информации о тестах
- Создать модель "Подписка" для отслеживания подписок пользователей на различные пакеты.
- При необходимости, разработать соответствующие фабрики и сиды для создания тестовых данных или инициализации моделей.
### **Критерии приёмки:**
- Модели успешно мигрированы в базу данных 
- Правильно описаны все связи
- Модели корректно связаны с друг другом 
- Сиды отрабатывают безошибочно 
### **Реальное время работы**

**Comment by khalfin1994** [comment]
Completed
