### ISSUE TITLE
Создание главной страницы "Менторство"

### ISSUE THREAD

**Issue by Timur211** [AttractorSchool/ESPD-APHP1#37]
### Конечный результат:
Создать главную страницу Менторство 
### План решения:
- Создать контроллер и блейд для данной страницы
- Создать соответствующий роут
- Создать отдельный файл стилей и расположить в resourses/sass
Шаблон-макет для реализации:
![image](https://github.com/AttractorSchool/ESPD-APHP1/assets/56838167/53f8a7e9-39ce-4a9b-abce-298476b1abdd)

### Критерии приёмки:
 - Блок с ссылкой на тест должен быть фиолетового цвета (#9653D9) и переходить на другую страницы (временно поставить заглушку)
 - Background цвета всей страницы: #FAF6FD
 - В блоке "Топ менторы" должны отображаться данные о топ менторах (имена), включая их рейтинг и интересы
 - Также в виде текста "Топ менторы" сделать ссылку на всех менторов (временно поставить заглушку)
 - В блоке "Рекомендуем вам" должны отображаться данные о рекомендуемых менторах, включая их рейтинг и интересы, в случае если нету менторов подходящих по интересу отображать соответственно только "Топ менторов"
### Реальное время работы

**Comment by khalfin1994** [comment]
Completed
