### ISSUE TITLE
Реализация страница с тестом

### ISSUE THREAD

**Issue by Timur211** [AttractorSchool/ESPD-APHP1#38]
### Конечный результат:
Создать страницу Тестирование
### План решения:
- Создать контроллер и блейд для данной страницы
- Создать соответствующий роут
- Создать отдельный файл стилей и расположить в resourses/sass
Шаблон-макет для реализации:
![image](https://github.com/AttractorSchool/ESPD-APHP1/assets/56838167/e4861097-f4c4-4a0c-b78b-6224bfeaf92e)

### Критерии приёмки:
 - Так как это тестовый вариант, достаточно 1 вопроса, переход на следующий вопрос сделать пожеланию 
 - Страница Тестирование должна отображать вопросы и варианты ответов
 - Функциональность сохранения результатов теста должна быть реализована и работать корректно.
 - Страница должна соответствовать предложенному макету (background: #FAF6FD)
 - Вёрстка не должна слетать
### Реальное время работы

**Comment by khalfin1994** [comment]
Нужно закончить верстку
