### ISSUE TITLE
Реализация подбора ментора и резидента по геолокации

### ISSUE THREAD

**Issue by Timur211** [AttractorSchool/ESPD-APHP1#39]
### **Конечный результат:**
Реализовать функционал геолокации в нетворкинге и в менторстве
### **План решения:**
- Создать выборку городов (дизайн произвольный, следовать общей стилистики сайта)
- Реализация функциональности на основа геолокации профиля
- Правильно реализованный запрос для верного подбора ментора и резидента
### **Критерии приёмки:**
- Пользователь может видеть менторов и резидентов на основе своей геолокации
- В случае если менторы и резиденты не совпадают по геолокации, можно просто отобразить всех резидентов
### **Реальное время работы**

**Comment by Amalbek00** [comment]
Done
