### ISSUE TITLE
Создание страницы Резидентов

### ISSUE THREAD

**Issue by Safi51** [AttractorSchool/ESPD-APHP1#4]
### Конечный результат:

- Реализовать верстку - дизайн страницы с всеми резидентами(начать для мобильного разрешения)

### План решения
- Реализовать резидентов в виде карточек с выведением модального окна с чем он занимается(возможно через foreach и добавление sweet alert для модального окна)
- Добавление прайс листа с модальными окнами на форму

### Критерии приёмки:
При нажатие на кнопку в главной страницы открывается страница резидентов

**Comment by Arystanbek360** [comment]
in proccess

**Comment by Arystanbek360** [comment]
done
