### ISSUE TITLE
Реализовать уведомление

### ISSUE THREAD

**Issue by Timur211** [AttractorSchool/ESPD-APHP1#43]
### Конечный результат:
Реализовать метод уведомления
### План решения:
- Тикет #22 который реализовывали ранее нужно будет сделать дополнительное уведомление по почте
- Логику с уведомлением можно продолжить доделать или переделать с нуля
- Внести необходимые изменения в код, связанный с тикетом #22, для добавления функциональности уведомления по электронной почте
- Также переделать вёрстку схожей с макетом:
![image](https://github.com/AttractorSchool/ESPD-APHP1/assets/56838167/26232a76-26be-4ac9-9d13-b20526a99255)

### Критерии приёмки:
- Уведомление по электронной почте должно быть добавлено в метод реализации тикета #22
- Уведомление по электронной почте должно быть успешно отправлено на указанный адрес
- Вёрстка соответствует макету и не съезжает

### Реальное время работы

**Comment by Amalbek00** [comment]
**Закончил верстку**
**Осталось реализовать отправку по почте**
