### ISSUE TITLE
Верстка регистрации и войти

### ISSUE THREAD

**Issue by Safi51** [AttractorSchool/ESPD-APHP1#5]
### Конечный результат:

- Реализовать верстку - страницы регистрации и войти (сначала для мобильной версии)

### Мотивация:

- Улучшение внешнего вида страницы регистрации и войти

### План решения:

- Реализовать верстку для регистрации
- Реализовать верстку для входа

Критерии приёмки:

-  При клике в навбаре на Sign up открывается войти
- При клике Членство открывается Регистрация

### Реальное время работы

**Comment by Arystanbek360** [comment]
done
