### ISSUE TITLE
Реализация Админ-панели

### ISSUE THREAD

**Issue by Amalbek00** [AttractorSchool/ESPD-APHP1#50]
### **Конечный результат:**
Реализовать Админ-панель 
### **План решения:**
- Загрузить необходимые библиотеки Orchid
- Создать учетную запись Админа
- Запуск админ-панели
### **Критерии приёмки:**
- Если пользователь не админ, его перенаправляют на страницу с ошибкой 403 (Forbidden)
- Если зайти под админом и перейти по ссылке \admin, то откроется админ-панель 
как примерно должна выглядить админ панель:

![image](https://github.com/AttractorSchool/ESPD-APHP1/assets/57621882/349f3d5c-946f-4ee7-ad43-456380c57658)

- На странице админ-панели должны отоброжаться список резидентов и менторов 
как примерно должнен выглядить список:

![image](https://github.com/AttractorSchool/ESPD-APHP1/assets/57621882/c5a7fc48-7288-42b7-81a6-6be46abc80a7)

### **Реальное время работы**

**Comment by Safi51** [comment]
### **Планируемое время-5ч**
### **Реальное время: 10ч**
