### ISSUE TITLE
Реализация кнопки автоматического сообщения

### ISSUE THREAD

**Issue by Amalbek00** [AttractorSchool/ESPD-APHP1#52]
### **Конечный результат:**
Реализация кнопки автоматического сообщения
### **План решения:**
- Сверстать кнопку   
- Расположить в окне чата
- Добавить функционал отправки сообщения
### **Критерии приёмки:**
- При условии что нету отправленных сообщений, при входе в чат открывается окно с кнопкой отправки:
Пример как в телеграмме (вместо стикера, использовать текст):

![image](https://github.com/AttractorSchool/ESPD-APHP1/assets/57621882/16aed6db-5592-4bd6-98e4-b6f8b96b4f67)

- При нажатии на кнопку отправить, отправляется сообщение 
Пример как в телеграмме (вместо стикера, использовать текст)

![image](https://github.com/AttractorSchool/ESPD-APHP1/assets/57621882/7f5013c0-5f4d-431e-a07d-30beea238c6d)

- Если сообщения уже отпраленны, то возможность отправить кнопкой пропадает, что и у отправителя, так и у получателя

### **Реальное время работы**

**Comment by Safi51** [comment]
### **Планируемое время: 3ч**
### **Конченое время: 4ч**
