### ISSUE TITLE
Разработка функционала подсчета авторизованных пользователей для статистики в Админ панеле

### ISSUE THREAD

**Issue by Amalbek00** [AttractorSchool/ESPD-APHP1#54]
### **Конечный результат:**
Админ панель должна содержать новую графу "Статистика авторизации" с возможностью выбора интервала по времени.
В данной статистике должно отображаться общее количество авторизованных пользователей за выбранный период.
### **План решения:**

- Создание таблицы в базе данных:
Создать новую таблицу для хранения информации о времени авторизации пользователей, включающую поля: (ID пользователя; Время авторизации). 

- Добавление записи при успешной авторизации:
На уровне приложения добавить логику, которая будет создавать запись в таблице "Статистика авторизации" при успешной авторизации пользователя.

- Разработка интерфейса Админ панели:
В Админ панеле добавить новую графу "Статистика авторизации" с возможностью выбора интервала по времени.

- Подсчет авторизованных пользователей:
Создать запрос к базе данных для подсчета количества записей в таблице "Статистика авторизации" за выбранный интервал времени, чтобы определить количество авторизованных пользователей.

### **Критерии приёмки:**
- Админ панель содержит новую графу "Статистика авторизации".
- Возможность выбора интервала по времени в Админ панели реализована корректно.
- При успешной авторизации пользователя создается запись в таблице "Статистика авторизации".
- Статистика о количестве авторизованных пользователей отображается корректно в Админ панели.

### **Реальное время работы**

**Comment by Safi51** [comment]
### **Ожидаемое время: 3ч**
### **Реальное время: 4ч**
