### ISSUE TITLE
Сверстать страницу профиля

### ISSUE THREAD

**Issue by Amalbek00** [AttractorSchool/ESPD-APHP1#57]
### **Конечный результат:**
Верстка страницы профиля (mobile first)

### **План решения:**
- Структура страницы: Определить общую структуру страницы, включая размещение фото, имени, фамилии, электронной почты, страны, города, номера телефона и интересов. Использовать семантические теги HTML для каждого элемента.
- Каскадные таблицы стилей (CSS): Написать CSS-стили для каждого элемента на странице, обеспечивая согласованный и приятный дизайн. Применить адаптивный дизайн, чтобы страница хорошо выглядела на различных устройствах.
- Изображение профиля: Создать стиль для фото профиля, обеспечивающий его отображение в хорошем качестве и правильное масштабирование на всех устройствах.
- Поля должны быть: фото профиля, имя, фамилию, электронную почту, страну, город, номер телефона и интересы.
Примерный макет:

![image](https://github.com/AttractorSchool/ESPD-APHP1/assets/57621882/da64ffbb-4734-4a5b-946d-8cefa75f3fc6)

### **Критерии приёмки:**
- Верстка страницы должна быть адаптивной и отзывчивой, чтобы хорошо выглядеть на различных устройствах, включая мобильные телефоны, планшеты и настольные компьютеры.
- Фото профиля должно отображаться без искажений и правильно масштабироваться на всех устройствах.
- Имя, фамилия, электронная почта, страна, город, номер телефона и интересы должны быть четко видимы и читаемы на всех разрешениях экрана.
- Стилизация элементов страницы должна соответствовать предоставленному дизайну.

**Comment by Timur211** [comment]
### **Планируемое время: 4ч**
### **Реальное время: 4ч**
