### ISSUE TITLE
Проектирование базы данных, создание сидов, фабрик для работы курсов, тестов, интересов, загрузки видео

### ISSUE THREAD

**Issue by khalfin1994** [AttractorSchool/ESPD-APHP1#66]
**Конечный результат:**

Создать миграции, сиды и фабрики для функциональной работы курсов, тестов, интересов, загрузки видео.

**План решения:**

- Добавить колонну "pictures" в таблицу Interests;
- Создать миграции для courses, videos, questions, answers. Добавить все необходимые колонны для этих миграций;
- Наполнить сидами и фабриками вышеперечисленные таблицы;
- Прописать в моделях необходимые связи;
- Добавить миграции для учета статистики пользователя;
- Доработать reviews для возможности отправки отзыва, после прохождения тестирования

_Примерная схема БД:_
![image](https://github.com/AttractorSchool/ESPD-APHP1/assets/131901415/e33dfec8-b631-48fc-b7da-860376ec177a)

**Критерии приёмки:**

- Проектирование БД должно быть максимально функциональным для текущей и последующих итераций;
- Должны быть реализованы сиды и фабрики для работы и демонстрации проделанной работы на встрече

**Планируемое время работы:**
10 ч.

**Реальное время работы:**

**Comment by Safi51** [comment]
### **Планируемое время: 4ч**
### **Реальное время: 4ч**
