### ISSUE TITLE
Реализация страницы всех курсов, страницы определенного курса

### ISSUE THREAD

**Issue by khalfin1994** [AttractorSchool/ESPD-APHP1#68]
**Конечный результат:**

Верстка должна быть в точности как в фигме, после выбора интереса, должны выводиться соответствующие курс, на этой странице должен быть поисковик, курс можно открыть, посмотреть всю информацию о нем и перейти к обучению.

**План решения:**

- Добавить фильтрацию по интересам - после выбора определенного курса, должна отработать фильтрация по выбранному интересу;
- На странице со списком курсов реализовать поисковик;
- Реализовать кнопку "Избранное", пока не создан "Мой кабинет", использовать заглушку;
- При нажатии на любой курс должна открыться страница  с курсом, на которой будут: отзывы и рейтинги, автор курса, материалы, описание.
- "Все отзывы" - Это ссылка, дизайн сделать на свой вкус, максимально приближенный к общему дизайну академии. Должно быть видно все отзывы этого курса;
- При открытии курса, снизу должна присутствовать кнопка "Начать курс", согласовать с @Safi51 и @Arystanbek360;
- Следуем мокапу. [Ссылка ](https://www.figma.com/file/lgPgWkABbcwq8AnPQTQgM4/%D0%A4%D0%BB%D0%BE%D1%83-%D1%80%D0%B5%D0%B7%D0%B8%D0%B4%D0%B5%D0%BD%D1%82%D0%B0-WCG-%22Network%22?type=design&node-id=0-1&mode=design&t=MmwulDKT4wb4mGyt-0) на фигму. 

_Мокапы страниц:_
![image](https://github.com/AttractorSchool/ESPD-APHP1/assets/131901415/dc5d0742-87f3-448c-aeab-20f619a9bfdf)
![image](https://github.com/AttractorSchool/ESPD-APHP1/assets/131901415/ce3b72ce-1d9c-41e8-a299-5c5e1e4d807f)

**Критерии приёмки:**

При переходе в академию, пользователя встречает окно с интересами, где можно выбрать несколько, в каждом интересе отображается сколько курсов по этому интересу имеется. Интересы записываются в базу данных. После выбора интересов, пользователя встречает страница с курсами, где отфильтрованы интересы, которые выбрал пользователь. На этой странице должен присутствовать поисковик, кликабельные карточки с курсами, у которых на бекграунде картинка,  в которых; название курса, описание, кнопка "лайк" с заглушкой для добавления в избранное для будущих итераций. При клике на курс, отрывается окно с курсом, где сверху располагается картинка, присутствует: кнопка "лайк", возможность вернуться назад, название, автор, длительность, рейтинг, отзывы. Также должна присутствовать ссылка на "все отзывы", где можно посмотреть список отзывов. Снизу должна располагаться кнопка "Начать курс".

**Планируемое время работы:**
30 ч.

**Реальное время работы:**

**Comment by Amalbek00** [comment]
Done!
