### ISSUE TITLE
Функционал добавления курсов через админ-панель Orchid

### ISSUE THREAD

**Issue by khalfin1994** [AttractorSchool/ESPD-APHP1#72]
**Конечный результат:**

У администратора появляется возможность добавлять курсы, видео к курсам, тесты к видео через админ-панель.

**План решения:**

- в админ-панели в разделе "курсы" можно добавить курс;
- в админ-панели в разделе "видео" можно добавить видео к курсу;
- в админ-панели в разделе "тесты" можно добавить тест к видео

**Критерии приёмки:**

В админ-панели в разделе "курсы", авторизовавшись, администратор может добавить курсы, к курсам можно добавить видео, а к видео тесты

**Планируемое время:**
20 ч.

**Реальное время:**
14 ч.

**Comment by Arystanbek360** [comment]
Реализовал: CRUD для модели Курс (работает без нарекании все валидируется,удаляется и создается без багов)
CRUD для модели Видео (работает тоже все отлично и показывает даже данные кто загружал видео подгружая пользователя из курса)(Проблема с загрузкой видео)
CRUD для модели Вопрос-Ответ(Вывод данных коректный и правильный и метод show тоже работает коректно,но метод Update,Save не работают и в самом блейде не получается сделать мультизагрузку чтобы можно было сразу загрузить вопрос и создать куча ответов через один блейд)(Crud работает для самих вопросов но не работает для ответов)

**Comment by Arystanbek360** [comment]
Времени было потрачено: 14 часов
