### ISSUE TITLE
Просмотр списка мероприятий

### ISSUE THREAD

**Issue by Arystanbek360** [AttractorSchool/ESPD-APHP1#81]
### **Конечный результат:**
 Реализация функционала просмотра списка мероприятий с возможностью фильтрации по дате и ответственным.
### **План решения:**
Разработать запросы для извлечения списка мероприятий из базы данных с учетом фильтрации.
Реализовать отображение списка мероприятий с возможностью фильтрации.

1. Разработка запросов и функциональности для получения списка мероприятий:

- Создание запросов к базе данных для извлечения списка мероприятий.
- Учет возможности фильтрации мероприятий по дате проведения и ответственному лицу.

2.Создание интерфейса списка мероприятий:

- Разработка пользовательского интерфейса для отображения списка мероприятий.
- Добавление элементов управления для фильтрации мероприятий по дате и ответственному.

3.Интеграция запросов с интерфейсом:

- Связывание запросов к базе данных с пользовательским интерфейсом для получения и отображения списка мероприятий.
<img width="763" alt="filter" src="https://github.com/AttractorSchool/ESPD-APHP1/assets/125344466/42ec890e-4aa4-4d40-bd41-5714319e5f04">

### **Критерии приёмки:**
Пользователь может просматривать список мероприятий и применять фильтры по дате и ответственным.
На страницу должны вывдоиться такие данные:
описание мероприятия, дата, локация, формат, стоимость
После нажатия на саму карточку с мероприятием открывается детальная страница просмотра мероприятия
### **Реальное время работы**

**Comment by Timur211** [comment]
### **Планируемое время-10ч**
### **Реальное время: 8ч**
