### ISSUE TITLE
Исправление NETWORK и сидов

### ISSUE THREAD

**Issue by Timur211** [AttractorSchool/ESPD-APHP1#92]
### **Конечный результат:**
Исправление NETWORK (mobile first) и сидов 

### **План решения:**
При переходе на линк резидентов, пофиксить всевозможные ошибки, пример на макете, если требуется затронуть бд
![photo_2023-08-14_11-01-53](https://github.com/AttractorSchool/ESPD-APHP1/assets/56838167/c858abd6-c1ff-4cf2-83e3-a586810c42bf)
При вводе команды fresh --seed выходит данная ошибка
![image](https://github.com/AttractorSchool/ESPD-APHP1/assets/56838167/1493d68b-2076-4ba3-b69e-e03d51040b64)
Решить данный вопрос связанный с сидами

### **Критерии приёмки:**
- Страница network корректно отображаются на мобильных устройствах
- Все резиденты выходят соответственно без ошибок
- Функциональность страниц корректно работают, элементы не съезжают 
- Сиды запускаются без ошибок
### **Реальное время работы**

**Comment by Amalbek00** [comment]
Done
