### ISSUE TITLE
Фикс вёрстки на главной странице

### ISSUE THREAD

**Issue by Timur211** [AttractorSchool/ESPD-APHP1#93]
### **Конечный результат:**
Фикс вёрстки на главной странице

### **План решения:**
![image](https://github.com/AttractorSchool/ESPD-APHP1/assets/56838167/05ddb703-1213-4ae6-9796-b425c459ec64)
При нажатии на FAQ вопросы, тарифы сворачиваются в гармошку, пофиксить вёрстку чтобы такого явление не было
Также при раскрывания сэндвич меню, уведомления располагаться должно справа от значка сэндвич меню как и на рисунке ниже, не должна съезжать
![image](https://github.com/AttractorSchool/ESPD-APHP1/assets/56838167/883a4b38-fe50-4ce1-900a-3555baf0aa5e)
![image](https://github.com/AttractorSchool/ESPD-APHP1/assets/56838167/8f0b7c5b-9d88-4db6-8fe8-ab743d72a35a)

### **Критерии приёмки:**
- Главная страница корректно отображаются на мобильных устройствах
- Вёрстка с тарифами не слетает
- Уведомление стоит статично и не съезжает 
### **Реальное время работы**

**Comment by Safi51** [comment]
Планируемое время работы:3ч
Реальное время работы:6ч
