### ISSUE TITLE
Реализация оставить заявку

### ISSUE THREAD

**Issue by Timur211** [AttractorSchool/ESPD-APHP1#94]
### **Конечный результат:**
Сделать кнопку оставить заявку активной и записывать данные в бд

### **План решения:**
На главной странице и странице резидентов сделать пользователю возможным оставить заявку, открывается окно с платёжкой, также стилизовать как на макете
![image](https://github.com/AttractorSchool/ESPD-APHP1/assets/56838167/01daa275-b780-4855-af27-d3e978e681b8)

![image](https://github.com/AttractorSchool/ESPD-APHP1/assets/56838167/ce3b6791-cda6-43b2-b41b-1f853c7207a1)

### **Критерии приёмки:**
- Перенаправить пользователя на страницу регистрации, если он не авторизован или не зарегистрирован, дальше перенаправить на окно с покупкой
- Данные сохраняются в бд корректно
- Вёрстка стилизовано как на макете
### **Реальное время работы**

**Comment by khalfin1994** [comment]
done
