### ISSUE TITLE
Личный кабинет

### ISSUE THREAD

**Issue by Safi51** [AttractorSchool/ESPD-APHP1#98]
### Конечный результат:
Сделать страничку личного кабинет

### Критерии приёмки:
![image](https://github.com/AttractorSchool/ESPD-APHP1/assets/108079889/921ddddc-e319-4124-a863-4a6db4697881)
При нажатие на профиль, открывается личный кабинет. В личном кабинете можно было бы 

- Менять свой профиль как в allbright. 
- Смотреть свои курсы.

### Реальное время работы

**Comment by Amalbek00** [comment]
Done
